title: Product
tabs:
  main:
    display: Content
    sections:
      -
        display: 'Header (Full Width)'
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              localizable: false
              validate:
                - required
          -
            handle: header
            field:
              import: editor
              display: 'Header Content'
              localizable: true
      -
        display: 'Left Column'
        fields:
          -
            handle: left_content
            field:
              type: replicator
              display: Inhaltselemente
              localizable: true
              collapse: true
              sets:
                main_elements:
                  display: Hauptelemente
                  icon: addon-boxes-stack
                  sets:
                    neues_set:
                      display: 'Neues Set'
                      fields: {  }
      -
        display: 'Right Column'
        fields:
          -
            handle: right_content
            field:
              type: replicator
              display: Inhaltselemente
              localizable: true
              collapse: true
              sets:
                main_elements:
                  display: Hauptelemente
                  icon: addon-boxes-stack
                  sets:
                    neues_set:
                      display: 'Neues Set'
                      fields: {  }
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: seo
  settings:
    display: Settings
    sections:
      -
        display: Settings
        fields:
          -
            import: settings
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
              show_regenerate: true
