title: Product
tabs:
  main:
    display: Content
    sections:
      -
        display: Content
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              localizable: false
              validate:
                - required
          -
            handle: main_image
            field:
              max_files: 1
              container: assets
              type: assets
              display: Hauptbild
              instructions: 'Wird als Vorschaubild auf der Übersichtsseite verwendet'
              localizable: false
              instructions_position: below
              folder: produkte
          -
            handle: images
            field:
              container: assets
              type: assets
              display: Bilder
              localizable: false
              width: 50
              folder: produkte
          -
            handle: content
            field:
              collapse: true
              type: replicator
              display: Inhalte
              localizable: false
              width: 50
              sets:
                main_elements:
                  display: Hauptelemente
                  icon: addon-boxes-stack
                  sets:
                    editor:
                      display: Text
                      instructions: 'Texteditor hinzufügen'
                      icon: text-formatting-markdown
                      fields:
                        -
                          import: editor
                    table:
                      display: Tabelle
                      instructions: 'Tabelle mit Zeilen'
                      icon: layout-table-row-insert
                      fields:
                        -
                          import: table
                    quote:
                      display: Zitat
                      instructions: 'Zitat mit Autor'
                      icon: text-formatting-quotation
                      fields:
                        -
                          import: quote
                    shop_opening_hours:
                      display: Ladenöffnungszeiten
                      instructions: Ladenöffnungszeiten
                      icon: text-formatting-initial-letter
                      fields:
                        -
                          import: shop_opening_hours
                    single_image:
                      display: Einzelbild
                      instructions: 'Einzelbild mit optionaler Legende'
                      icon: media-image-picture-orientation
                      fields:
                        -
                          import: single_image
                    spacer:
                      display: Spacer
                      icon: layout-split-horizontal
                      fields: {  }
  seo:
    display: SEO
    sections:
      -
        display: SEO
        fields:
          -
            import: seo
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
              show_regenerate: true
          -
            handle: parent
            field:
              type: entries
              collections:
                - products
              max_items: 1
              listable: false
              localizable: true
